site_name: Design Specs (RFCs)
site_description: Repository of design specifications (RFCs)
site_url: https://your-org.github.io/design-specs/
docs_dir: .

theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
  palette:
    scheme: default
    primary: blue
    accent: indigo

repo_name: your-org/design-specs
repo_url: https://github.com/your-org/design-specs

nav:
  - Home: README.md
  - Process: PROCESS.md
  - Template: TEMPLATE.md
  - Active RFCs: RFC_INDEX.md
  - In Progress RFCs: IN_PROGRESS_INDEX.md
  - Archived RFCs: archive/RFC_ARCHIVE_INDEX.md

plugins:
  - search
  - awesome-pages
  - mermaid2

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
