blank_issues_enabled: false
contact_links:
  - name: 📘 RFC Process Guide
    url: https://github.com/your-org/design-specs/blob/main/PROCESS.md
    about: Read how RFCs are proposed, reviewed, and approved
  - name: 📑 RFC Template
    url: https://github.com/your-org/design-specs/blob/main/TEMPLATE.md
    about: Review the RFC template before drafting your proposal
