name: New RFC Auto Setup

on:
  issues:
    types: [opened]

jobs:
  create-rfc:
    if: contains(github.event.issue.title, 'RFC Proposal:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq jq

      - name: Extract issue fields
        id: fields
        run: |
          TITLE=$(echo "${{ github.event.issue.title }}" | sed 's/RFC Proposal: //')
          AUTHOR="${{ github.event.issue.user.login }}"
          DATE=$(date +%F)

          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "author=$AUTHOR" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Extract squads from labels
        id: squads
        run: |
          SQUADS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name' | grep '^squad/' | sed 's/squad\///' | xargs)
          echo "squads=$SQUADS" >> $GITHUB_OUTPUT
          echo "Detected squads: $SQUADS"

      - name: Generate RFC ID
        id: id
        run: |
          LAST=$(ls rfcs/RFC-* -1d 2>/dev/null | wc -l)
          NEXT=$((LAST+1))
          ID="RFC-$(printf "%03d" $NEXT)"
          echo "id=$ID" >> $GITHUB_OUTPUT

      - name: Create RFC skeleton
        run: |
          ID=${{ steps.id.outputs.id }}
          TITLE=${{ steps.fields.outputs.title }}
          AUTHOR=${{ steps.fields.outputs.author }}
          DATE=${{ steps.fields.outputs.date }}
          SQUADS=${{ steps.squads.outputs.squads }}

          DIR="rfcs/$ID-${TITLE// /-}"
          mkdir -p "$DIR/diagrams" "$DIR/design" "$DIR/notes"

cat > "$DIR/$ID-${TITLE// /-}.md" <<EOF
# $ID: $TITLE

## 📌 Metadata
- **RFC ID**: $ID
- **Title**: $TITLE
- **Author(s)**: $AUTHOR
- **Created Date**: $DATE
- **Status**: Draft
- **Version**: v1.0
- **Squads**: ${SQUADS:-TBD}

---
## 1. Motivation
(TODO)
...
EOF

      - name: Push branch
        run: |
          ID=${{ steps.id.outputs.id }}
          TITLE=${{ steps.fields.outputs.title }}
          BRANCH="rfc/${ID}-${TITLE// /-}"
          git checkout -b "$BRANCH"
          git add rfcs/
          git commit -m "chore: add skeleton for $ID"
          git push origin "$BRANCH"

      - name: Collect reviewers from squads
        id: reviewers
        run: |
          REVIEWERS=""
          CHECKLIST=""
          for squad in ${{ steps.squads.outputs.squads }}; do
            r=$(yq ".${squad}.reviewers[]" .github/squad-reviewers.yml | xargs || true)
            REVIEWERS="$REVIEWERS $r"
            CHECKLIST="$CHECKLIST\n- [ ] ${squad^} review"
          done
          echo "reviewers=$REVIEWERS" >> $GITHUB_OUTPUT
          echo "checklist=$CHECKLIST" >> $GITHUB_OUTPUT

      - name: Create draft PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "${{ steps.id.outputs.id }}: ${{ steps.fields.outputs.title }}"
          branch: "rfc/${{ steps.id.outputs.id }}-${{ steps.fields.outputs.title// /- }}"
          draft: true
          labels: |
            rfc
            proposal
            ${{ steps.squads.outputs.squads }}
          reviewers: ${{ steps.reviewers.outputs.reviewers }}
          body: |
            Auto-generated RFC skeleton from [issue #${{ github.event.issue.number }}](${{ github.event.issue.html_url }})

            **Author**: @${{ steps.fields.outputs.author }}  
            **Squads**: ${{ steps.squads.outputs.squads }}  
            **Status**: Draft  

            ---
            ## ✅ Review Checklist
            ${{ steps.reviewers.outputs.checklist }}
