name: RFC Squad Labeler

on:
  issues:
    types: [opened, edited]

jobs:
  label-squads:
    if: contains(github.event.issue.title, 'RFC Proposal:')
    runs-on: ubuntu-latest

    steps:
      - name: Extract squads from issue body
        id: squads
        run: |
          BODY="${{ github.event.issue.body }}"
          LABELS=""

          if echo "$BODY" | grep -q "\- \[x\] Foundry"; then
            LABELS="$LABELS squad/foundry"
          fi
          if echo "$BODY" | grep -q "\- \[x\] SDK"; then
            LABELS="$LABELS squad/sdk"
          fi
          if echo "$BODY" | grep -q "\- \[x\] Iris"; then
            LABELS="$LABELS squad/iris"
          fi
          if echo "$BODY" | grep -q "\- \[x\] Flare"; then
            LABELS="$LABELS squad/flare"
          fi

          echo "labels=$LABELS" >> $GITHUB_OUTPUT

      - name: Apply squad labels
        if: steps.squads.outputs.labels != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.squads.outputs.labels }}

      - name: Trigger RFC Skeleton Workflow
        if: steps.squads.outputs.labels != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "new-rfc.yml",
              ref: "main",
              inputs: {
                issue: JSON.stringify(context.payload.issue),
                labels: "${{ steps.squads.outputs.labels }}"
              }
            })