name: Update RFC Indexes & Badges

on:
  push:
    branches:
      - main
    paths:
      - "docs/rfcs/**"
      - "docs/archive/**"
      - "docs/README.md"

  workflow_run:
    workflows: ["RFC PR Checks"]
    types:
      - completed

jobs:
  update-indexes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Count and Categorize RFCs
        id: count
        run: |
          ACTIVE=0
          PROGRESS=0
          ARCHIVED=0
          TOTAL=0

          mkdir -p docs/archive

          for f in docs/rfcs/RFC-*/RFC-*.md docs/archive/RFC-*/RFC-*.md; do
            [ -f "$f" ] || continue
            TOTAL=$((TOTAL+1))

            STATUS=$(grep -m1 "Status" "$f" | cut -d':' -f2- | xargs || true)
            STATUS=$(echo "$STATUS" | tr '[:upper:]' '[:lower:]')

            case "$STATUS" in
              draft|in\ review) PROGRESS=$((PROGRESS+1)) ;;
              superseded|deprecated) ARCHIVED=$((ARCHIVED+1)) ;;
              *) ACTIVE=$((ACTIVE+1)) ;;
            esac
          done

          echo "active=$ACTIVE" >> $GITHUB_OUTPUT
          echo "progress=$PROGRESS" >> $GITHUB_OUTPUT
          echo "archived=$ARCHIVED" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT

      - name: Generate Indexes
        run: |
          echo "### 📑 Active RFCs" > docs/RFC_INDEX.md
          echo "" >> docs/RFC_INDEX.md
          echo "| RFC ID | Title | Status |" >> docs/RFC_INDEX.md
          echo "|--------|-------|--------|" >> docs/RFC_INDEX.md

          echo "### 📑 In Progress RFCs" > docs/IN_PROGRESS_INDEX.md
          echo "" >> docs/IN_PROGRESS_INDEX.md
          echo "| RFC ID | Title | Status |" >> docs/IN_PROGRESS_INDEX.md
          echo "|--------|-------|--------|" >> docs/IN_PROGRESS_INDEX.md

          echo "### 📑 Archived RFCs" > docs/archive/RFC_ARCHIVE_INDEX.md
          echo "" >> docs/archive/RFC_ARCHIVE_INDEX.md
          echo "| RFC ID | Title | Status |" >> docs/archive/RFC_ARCHIVE_INDEX.md
          echo "|--------|-------|--------|" >> docs/archive/RFC_ARCHIVE_INDEX.md

          for f in docs/rfcs/RFC-*/RFC-*.md docs/archive/RFC-*/RFC-*.md; do
            [ -f "$f" ] || continue
            ID=$(basename "$f" .md)
            TITLE=$(grep -m1 "^# " "$f" | sed 's/# //')
            STATUS=$(grep -m1 "Status" "$f" | cut -d':' -f2- | xargs || true)
            STATUS_LOWER=$(echo "$STATUS" | tr '[:upper:]' '[:lower:]')

            if [[ "$f" == docs/rfcs/* ]]; then
              LINK_PATH=$(echo "$f" | sed 's|^docs/||')   # -> rfcs/...
            else
              LINK_PATH=$(echo "$f" | sed 's|^docs/||')   # -> archive/...
            fi

            row="| [$ID]($LINK_PATH) | $TITLE | ${STATUS:-Draft} |"

            case "$STATUS_LOWER" in
              draft|in\ review) echo "$row" >> docs/IN_PROGRESS_INDEX.md ;;
              superseded|deprecated) echo "$row" >> docs/archive/RFC_ARCHIVE_INDEX.md ;;
              *) echo "$row" >> docs/RFC_INDEX.md ;;
            esac
          done

      - name: Update README Badges
        run: |
          TOTAL=${{ steps.count.outputs.total }}
          ACTIVE=${{ steps.count.outputs.active }}
          PROGRESS=${{ steps.count.outputs.progress }}
          ARCHIVED=${{ steps.count.outputs.archived }}

          # Docs site base (inject dynamically later if you use __PAGES_URL__)
          PAGES_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}"

          # Update badge lines in root README.md
          sed -i "s|!\[RFCs.*|[![RFCs](https://img.shields.io/badge/RFCs-${TOTAL}-blue)](${PAGES_URL}/RFC_INDEX.md)|" README.md
          sed -i "s|!\[Active.*|[![Active](https://img.shields.io/badge/Active-${ACTIVE}-green)](${PAGES_URL}/RFC_INDEX.md)|" README.md
          sed -i "s|!\[InProgress.*|[![In Progress](https://img.shields.io/badge/In%20Progress-${PROGRESS}-yellow)](${PAGES_URL}/IN_PROGRESS_INDEX.md)|" README.md
          sed -i "s|!\[Archived.*|[![Archived](https://img.shields.io/badge/Archived-${ARCHIVED}-lightgrey)](${PAGES_URL}/archive/RFC_ARCHIVE_INDEX.md)|" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/RFC_INDEX.md docs/IN_PROGRESS_INDEX.md docs/archive/RFC_ARCHIVE_INDEX.md README.md
          git commit -m "chore: update RFC indexes & badges" || echo "No changes"
          git push
